[project]
name = "data-dashboard"
version = "0.1.0"
requires-python = ">=3.13"
dependencies = [
    "polars>=1.26.0",
]

[tool.basedpyright]
include = ["src/data/vacc_refusal.csv.py"]
reportUnknownMemberType = false
